version: "3.9"

services:

  discoverus:
    build: .
    container_name: discoverus
    depends_on:
      - "redis" 
    ports: 
      - "2000:2000"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"