version: "3.9"

services:

  discoverus:
    build: .
    container_name: discoverus
    depends_on:
      - "redis" 
    ports: 
      - "2000:2000"
  redis-services:
    image: redis
    container_name: redis-services
    ports:
      - "6379:6379"
  redis-instances:
    image: redis
    container_name: redis-instances
    ports:
      - "6379:6379"
  redis-registry:
    image: redis
    container_name: redis-registry
    ports:
      - "6379:6379"