version: "3.9"

services:

  discoverus:
    build: .
    container_name: discoverus
    networks:
      - main
    depends_on:
      - "redis" 
    ports: 
      - "2000:2000"
  redis-services:
    image: redis
    container_name: redis-services
    networks:
      - main
  redis-instances:
    image: redis
    container_name: redis-instances
    networks:
      - main
  redis-registry:
    image: redis
    container_name: redis-registry
    networks:
      - main

networks:
  main:
    driver: bridge