version: "3.9"

services:

  redis-services:
    image: redis
    container_name: redis-services
    networks:
      - main

  redis-instances:
    image: redis
    container_name: redis-instances
    networks:
      - main

  redis-registry:
    image: redis
    container_name: redis-registry
    networks:
      - main

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=redis-app

    networks:
      - main


  discoverus:
    build: .
    container_name: discoverus
    networks:
      - main
    ports: 
      - "2000:2000"

networks:
  main:
    driver: bridge